# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Contract.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43ontract.proto\x12\x0c\x62\x61sket_event\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n\x1f\x42\x61sketConfirmedIntegrationEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12/\n\x0boccurred_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tbasket_id\x18\x04 \x01(\t\x12&\n\x07\x61\x64\x64ress\x18\x05 \x01(\x0b\x32\x15.basket_event.Address\x12!\n\x05items\x18\x06 \x03(\x0b\x32\x12.basket_event.Item\x12\x35\n\x0f\x64\x65livery_period\x18\x07 \x01(\x0b\x32\x1c.basket_event.DeliveryPeriod\x12\x0e\n\x06volume\x18\x08 \x01(\x05\"Z\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0e\n\x06street\x18\x03 \x01(\t\x12\r\n\x05house\x18\x04 \x01(\t\x12\x11\n\tapartment\x18\x05 \x01(\t\"S\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07good_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"*\n\x0e\x44\x65liveryPeriod\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x42\x43\n\rqueues.basketB\x11\x42\x61sketEventsProtoZ\x0fqueues/basketpb\xaa\x02\rQueues.Basketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rqueues.basketB\021BasketEventsProtoZ\017queues/basketpb\252\002\rQueues.Basket'
  _globals['_BASKETCONFIRMEDINTEGRATIONEVENT']._serialized_start=66
  _globals['_BASKETCONFIRMEDINTEGRATIONEVENT']._serialized_end=351
  _globals['_ADDRESS']._serialized_start=353
  _globals['_ADDRESS']._serialized_end=443
  _globals['_ITEM']._serialized_start=445
  _globals['_ITEM']._serialized_end=528
  _globals['_DELIVERYPERIOD']._serialized_start=530
  _globals['_DELIVERYPERIOD']._serialized_end=572
# @@protoc_insertion_point(module_scope)
